name: Deploy Documentation

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Unity in Docker and copy DLLs
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            unityci/editor:ubuntu-2022.3.42f1-base-3.1.0 \
            /bin/bash -c "mkdir -p /workspace/Documentation~/libs && \
                          cp ./opt/unity/Editor/Data/Managed/UnityEngine/UnityEngine.dll /workspace/Documentation~/libs/ && \
                          cp ./opt/unity/Editor/Data/Managed/UnityEngine/UnityEditor.dll /workspace/Documentation~/libs/"

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Install DocFX
        run: |
          dotnet tool install -g docfx --version 2.61.0
          echo "${{ runner.environment.HOME }}/.dotnet/tools" >> $GITHUB_PATH

      - name: Build Documentation
        run: |
          docfx Documentation~/docfx.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages